project:
  type: website
  output-dir: docs

website:
  title: "Lasse Leskelä"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: en/index.qmd
        text: English
      - href: fi/index.qmd
        text: suomi

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



