project:
  type: website
  output-dir: ../docs/fi

website:
  title: "Lasse Leskelä"

  navbar:
    left:
      - href: index.qmd
        text: Etusivu
      - href: tutkimus.qmd
        text: Tutkimus
      - href: julkaisut.qmd
        text: Julkaisut
      - href: opetus.qmd
        text: Opetus
    right:
      - href: ../en/
        text: EN

lang: fi

bibliography: ../data/publications.bib

csl: ../data/apa.csl

format:
  html:
    toc: false
